export const STORAGE_LANGUAGE = 'AND2.LANGUAGE';
export const STORAGE_THEME = 'AND2.THEME';
export const STORAGE_TUTORIAL = 'AND2.DID_TUTORIAL';
export const STORAGE_START_DATE = 'AND2.START_DATE';
export const STORAGE_END_DATE = 'AND2.END_DATE';
export const START_SECRET_KEY = 'AND2.SECRET_KEY';
